### ISSUE TITLE
Moving from `heroku` ro `railway`

### ISSUE THREAD

**Issue by hoaibao44** [didivu-vn/didivu-wiki#4]
https://divupro-apidjangobe-production.up.railway.app/admin/

**Comment by hoaibao44** [comment]
@xuanthai91 
https://railway.app/invite/1DwB6x3o4bW

We are moving away from `heroku`.
`railway` provide the same as `heroku` but cheaper.
Take a look.

**Comment by hoaibao44** [comment]
- [x] migrate database from heroku to railway, should we reset db?
- [x] check every thing all over again -> may be should research and apply unit test

**Comment by xuanthai91** [comment]
Good to hear that ::cheer
But all BE's url will change, right? So i will check it back for my app.

**Comment by hoaibao44** [comment]
yes, use this one please.
[https://divupro-apidjangobe-production.up.railway.app/](https://divupro-apidjangobe-production.up.railway.app/admin/)

**Comment by hoaibao44** [comment]
by the way, let me know if you can access to `railway` dashboard or not

**Comment by xuanthai91** [comment]
yup, i can access all of service of `railway ` now
and i'm reading document before change or create something

**Comment by hoaibao44** [comment]
@didivu-vn/didivu_devteam 
I moved both FE, BE and DB to railway.
Heroku no longer serving us anything.

Good by good old heroku.
I close this task.
